import { defineConfig } from "tinacms";

const branch =
  process.env.GITHUB_BRANCH ||
  process.env.VERCEL_GIT_COMMIT_REF ||
  process.env.HEAD ||
  "main";

export default defineConfig({
  branch,
  clientId: process.env.PUBLIC_TINA_CLIENT_ID || "",
  token: process.env.TINA_TOKEN || "",
  build: {
    outputFolder: "admin",
    publicFolder: "public",
  },
  media: {
    tina: {
      mediaRoot: "uploads",
      publicFolder: "public",
    },
  },
  schema: {
    collections: [
      {
        name: "page",
        label: "Obsah webu",
        path: "content/pages",
        format: "json",
        ui: {
          router: ({ document }) => {
            if (document._sys.filename === "home") {
              return "/";
            }
            return undefined;
          },
        },
        fields: [
          {
            type: "string",
            name: "title",
            label: "Název stránky (SEO Titulek)",
            isTitle: true,
            required: true,
          },
          {
            type: "object",
            name: "navbar",
            label: "Hlavička & Navigace",
            fields: [
              { type: "string", name: "brandName", label: "Název značky" },
              { type: "string", name: "brandTagline", label: "Podtitul značky" },
              { type: "string", name: "ctaText", label: "Text tlačítka v menu" },
              {
                type: "object",
                name: "navLinks",
                label: "Odkazy v horním menu",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.label || "Odkaz" }),
                },
                fields: [
                  { type: "string", name: "label", label: "Text odkazu" },
                  { type: "string", name: "href", label: "Cíl odkazu (#sekce)" },
                  { type: "string", name: "badge", label: "Štítek (např. 1. zdarma)" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "hero",
            label: "Hero sekce",
            fields: [
              { type: "string", name: "badge", label: "Horní odznáček / Tagline" },
              { type: "string", name: "title", label: "Hlavní nadpis" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "ctaPrimaryText", label: "Text primárního tlačítka" },
              { type: "string", name: "ctaPrimaryLink", label: "Odkaz primárního tlačítka" },
              { type: "string", name: "ctaSecondaryText", label: "Text sekundárního tlačítka" },
              { type: "string", name: "ctaSecondaryLink", label: "Odkaz sekundárního tlačítka" },
              {
                type: "object",
                name: "card",
                label: "Karta Josefa & Hlasová ukázka (vpravo)",
                fields: [
                  { type: "boolean", name: "enabled", label: "Zobrazit kartu Josefa v Hero na webu?" },
                  { type: "boolean", name: "showBenefits", label: "Zobrazit v kartě spodní minikarty výhod a adresu?" },
                  { type: "image", name: "image", label: "Fotka / Avatar lektora v Hero" },
                  { type: "string", name: "teacherName", label: "Jméno lektora" },
                  { type: "string", name: "teacherRole", label: "Podtitul / Vzdělání (např. BBA Melbourne • 25+ let v ČR)" },
                  { type: "string", name: "teacherTag", label: "Specializace (např. Australský přízvuk & výuka hrou)" },
                  { type: "string", name: "badgeText", label: "Odznáček na kartě (např. 1. lekce ZDARMA)" },
                  {
                    type: "object",
                    name: "audio",
                    label: "Hlasový přehrávač Josefa",
                    fields: [
                      { type: "string", name: "title", label: "Nadpis přehrávače zvuku" },
                      { type: "string", name: "subtitlePrompt", label: "Výzva k přehrání (např. Klikněte pro přehrání)" },
                      {
                        type: "object",
                        name: "phrases",
                        label: "Zvukové fráze",
                        list: true,
                        ui: {
                          itemProps: (item) => ({ label: `${item?.buttonLabel || item?.id || "Fráze"}` }),
                        },
                        fields: [
                          { type: "string", name: "id", label: "Klíč zvuku (gday, dice, noworries)" },
                          { type: "string", name: "buttonLabel", label: "Text na tlačítku" },
                          { type: "string", name: "short", label: "Zkrácený text u vln" },
                          { type: "string", name: "en", label: "Anglická věta", ui: { component: "textarea" } },
                          { type: "string", name: "cz", label: "Český překlad věty", ui: { component: "textarea" } },
                        ],
                      },
                    ],
                  },
                  { type: "string", name: "benefit1Title", label: "Výhoda 1 - Nadpis" },
                  { type: "string", name: "benefit1Desc", label: "Výhoda 1 - Podtitul" },
                  { type: "string", name: "benefit2Title", label: "Výhoda 2 - Nadpis" },
                  { type: "string", name: "benefit2Desc", label: "Výhoda 2 - Podtitul" },
                  { type: "string", name: "locationNote", label: "Adresa v kartě" },
                  { type: "string", name: "onlineNote", label: "Online text v kartě" },
                  { type: "string", name: "ctaText", label: "Text odkazu (např. Rezervovat →)" },
                  { type: "string", name: "ctaLink", label: "Cíl odkazu" },
                ],
              },
              {
                type: "object",
                name: "stats",
                label: "Statistiky & Důvěryhodnost",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: `${item?.number || "Statistika"} - ${item?.label || ""}` }),
                },
                fields: [
                  { type: "string", name: "number", label: "Číslo (např. 10+ let)" },
                  { type: "string", name: "label", label: "Popis (např. praxe v ČR)" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "audience",
            label: "3 Cílové skupiny (ZŠ, SŠ, Dospělí)",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci Programy & Hry na webu?" },
              { type: "string", name: "badge", label: "Odznáček sekce" },
              { type: "string", name: "title", label: "Nadpis sekce" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "cohortTabsLabel", label: "Mobilní přepínač ročníků - nadpis" },
              { type: "string", name: "gamesLabel", label: "Karta programu - nadpis her" },
              { type: "string", name: "pointsLabel", label: "Karta programu - nadpis výhod" },
              { type: "string", name: "guaranteeLabel", label: "Karta programu - spodní garance" },
              {
                type: "object",
                name: "kidsPrograms",
                label: "Programy pro žáky ZŠ",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: `${item?.title || "Program"} (${item?.age || ""})` }),
                },
                fields: [
                  { type: "string", name: "id", label: "Identifikátor" },
                  { type: "string", name: "icon", label: "Ikona / Emoji" },
                  { type: "image", name: "image", label: "Obrázek programu (ilustrace / fotka)" },
                  { type: "string", name: "title", label: "Název programu" },
                  { type: "string", name: "age", label: "Věk a velikost skupinky" },
                  { type: "string", name: "badge", label: "Štítek" },
                  { type: "string", name: "highlight", label: "Hlavní tahák / přínos" },
                  { type: "string", name: "description", label: "Popis programu", ui: { component: "textarea" } },
                  { type: "string", name: "games", label: "Představené hry", list: true },
                  { type: "string", name: "points", label: "Body výhod", list: true },
                  { type: "string", name: "capacityNote", label: "Stav volných míst (např. 🟢 Volná 3 místa)" },
                  { type: "string", name: "ctaText", label: "Text tlačítka" },
                  { type: "string", name: "ctaLink", label: "Odkaz tlačítka" },
                ],
              },
              {
                type: "object",
                name: "waitingList",
                label: "Čekací listina pro SŠ a dospělé",
                fields: [
                  { type: "string", name: "badge", label: "Štítek" },
                  { type: "string", name: "title", label: "Nadpis" },
                  { type: "string", name: "description", label: "Popis", ui: { component: "textarea" } },
                  { type: "string", name: "ctaText", label: "Text tlačítka" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "scio",
            label: "Sekce SCIO & Přijímačky na SŠ",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci SCIO na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Hlavní nadpis" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "tagline", label: "Slogan" },
              { type: "string", name: "features", label: "Body a výhody přípravy", list: true },
              { type: "string", name: "ctaText", label: "Text tlačítka" },
              { type: "string", name: "ctaLink", label: "Odkaz tlačítka" },
            ],
          },
          {
            type: "object",
            name: "about",
            label: "Sekce O lektorovi & Metodika",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci O lektorovi na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Nadpis sekce" },
              { type: "image", name: "image", label: "Hlavní fotka lektora Josefa" },
              { type: "string", name: "teacherName", label: "Jméno lektora" },
              { type: "string", name: "role", label: "Titul / Pozice" },
              { type: "string", name: "bio", label: "Životopis a přístup", ui: { component: "textarea" } },
              { type: "string", name: "quote", label: "Citát / Motto", ui: { component: "textarea" } },
              { type: "string", name: "quoteAuthor", label: "Autor citátu" },
              { type: "string", name: "ctaText", label: "Text tlačítka 1. lekce" },
              { type: "string", name: "locationNote", label: "Poznámka s adresou" },
              {
                type: "object",
                name: "credentials",
                label: "Karta zkušeností (Proč se učit s Josefem)",
                fields: [
                  { type: "string", name: "title", label: "Nadpis karty" },
                  { type: "string", name: "subtitle", label: "Podtitul" },
                  { type: "string", name: "points", label: "Body zkušeností", list: true },
                  { type: "string", name: "note", label: "Spodní poznámka" },
                  { type: "string", name: "guarantee", label: "Zvýrazněný text (1. lekce ZDARMA)" },
                ],
              },
              {
                type: "object",
                name: "pillars",
                label: "4 Pilíře výuky",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Pilíř" }),
                },
                fields: [
                  { type: "string", name: "icon", label: "Ikona / Emoji" },
                  { type: "string", name: "title", label: "Název pilíře" },
                  { type: "string", name: "description", label: "Popis pilíře", ui: { component: "textarea" } },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "pricing",
            label: "Ceník a balíčky",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci Ceník na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Nadpis sekce" },
              { type: "string", name: "subtitle", label: "Podnadpis sekce", ui: { component: "textarea" } },
              { type: "string", name: "tabsLabel", label: "Mobilní přepínač ceníku - nadpis" },
              { type: "string", name: "featuresLabel", label: "Karta ceníku - nadpis položek v ceně" },
              { type: "string", name: "guarantee", label: "Garance spokojenosti", ui: { component: "textarea" } },
              {
                type: "object",
                name: "tiers",
                label: "Cenové balíčky",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: `${item?.name || "Balíček"} - ${item?.price || ""}` }),
                },
                fields: [
                  { type: "string", name: "name", label: "Název balíčku" },
                  { type: "string", name: "price", label: "Cena" },
                  { type: "string", name: "period", label: "Čas / Počet lekcí" },
                  { type: "string", name: "description", label: "Popis balíčku", ui: { component: "textarea" } },
                  { type: "boolean", name: "isPopular", label: "Zvýraznit jako nejpopulárnější?" },
                  { type: "string", name: "badge", label: "Štítek" },
                  { type: "string", name: "features", label: "Položky v ceně", list: true },
                  { type: "string", name: "ctaText", label: "Text tlačítka" },
                  { type: "string", name: "ctaLink", label: "Odkaz tlačítka" },
                ],
              },
              {
                type: "object",
                name: "pillars",
                label: "3 Garance ceníku (dole)",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Garance" }),
                },
                fields: [
                  { type: "string", name: "icon", label: "Ikona (emoji)" },
                  { type: "string", name: "title", label: "Název" },
                  { type: "string", name: "desc", label: "Popis", ui: { component: "textarea" } },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "comparison",
            label: "Srovnávací tabulka (Škola vs Doučování vs Valek)",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit Srovnávací tabulku na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Nadpis srovnání" },
              { type: "string", name: "subtitle", label: "Podnadpis srovnání", ui: { component: "textarea" } },
              { type: "string", name: "ctaText", label: "Text tlačítka 1. lekce (vítěz)" },
              { type: "string", name: "ctaLink", label: "Odkaz tlačítka (vítěz)" },
              { type: "string", name: "toggleButtonText", label: "Text tlačítka pro mobilní srovnání" },
              { type: "string", name: "labelSpeakingTime", label: "Popisek: Mluvení a prostor pro řeč" },
              { type: "string", name: "labelAtmosphere", label: "Popisek: Atmosféra & stres" },
              { type: "string", name: "labelMethod", label: "Popisek: Metodika výuky" },
              { type: "string", name: "labelAccent", label: "Popisek: Přízvuk a lektor" },
              { type: "string", name: "labelMotivation", label: "Popisek: Motivace dítěte" },
              {
                type: "object",
                name: "columns",
                label: "Srovnávací sloupce",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Sloupec" }),
                },
                fields: [
                  { type: "string", name: "type", label: "Typ (school, private, valek)" },
                  { type: "string", name: "title", label: "Název" },
                  { type: "string", name: "subtitle", label: "Podtitul (počet dětí)" },
                  { type: "string", name: "badge", label: "Štítek" },
                  { type: "string", name: "price", label: "Cena" },
                  { type: "string", name: "priceNote", label: "Poznámka k ceně" },
                  { type: "string", name: "speakingTime", label: "Prostor pro mluvení" },
                  { type: "string", name: "atmosphere", label: "Atmosféra & stres" },
                  { type: "string", name: "method", label: "Metodika & hry" },
                  { type: "string", name: "accent", label: "Přízvuk lektora" },
                  { type: "string", name: "motivation", label: "Motivace & výsledky" },
                  { type: "string", name: "footerNote", label: "Spodní poznámka karty" },
                  { type: "boolean", name: "isWinner", label: "Je vítěz srovnání? (Zlaté zvýraznění)" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "testimonials",
            label: "Reference a recenze",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci Reference na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Nadpis sekce" },
              { type: "string", name: "subtitle", label: "Podnadpis sekce", ui: { component: "textarea" } },
              { type: "string", name: "ratingScore", label: "Skóre hodnocení" },
              { type: "string", name: "ratingNote", label: "Poznámka k hodnocení" },
              {
                type: "object",
                name: "reviews",
                label: "Recenze studentů a rodičů",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: `${item?.name || "Student"} (${item?.role || ""})` }),
                },
                fields: [
                  { type: "string", name: "name", label: "Jméno studenta / rodiče" },
                  { type: "string", name: "role", label: "Pozice / Role a město" },
                  { type: "string", name: "location", label: "Město" },
                  { type: "number", name: "rating", label: "Počet hvězdiček (1-5)" },
                  { type: "string", name: "highlight", label: "Hlavní přínos / Zvýraznění" },
                  { type: "string", name: "quote", label: "Citace / Zkušenost", ui: { component: "textarea" } },
                  { type: "string", name: "avatarText", label: "Iniciály" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "howItWorks",
            label: "Metodika & Hry",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci Jak výuka hrou funguje na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Hlavní nadpis" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "quote", label: "Citát / Zvýrazněná věta" },
              { type: "string", name: "gamesTitle", label: "Nadpis představených her" },
              { type: "string", name: "gamesSubtitle", label: "Podnadpis představených her" },
              { type: "string", name: "phrasesLabel", label: "Popisek ukázkových vět" },
              {
                type: "object",
                name: "gameSpotlights",
                label: "Představené deskovky",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Deskovka" }),
                },
                fields: [
                  { type: "string", name: "icon", label: "Ikona / Emoji" },
                  { type: "string", name: "title", label: "Název hry" },
                  { type: "string", name: "tag", label: "Zaměření" },
                  { type: "string", name: "badge", label: "Štítek / Věk" },
                  { type: "string", name: "accent", label: "Barevný akcent (CSS třída)" },
                  { type: "string", name: "desc", label: "Popis přínosu", ui: { component: "textarea" } },
                  { type: "string", name: "phrases", label: "Ukázky vět ze hry", list: true },
                ],
              },
              {
                type: "object",
                name: "steps",
                label: "3 Kroky lekce",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Krok" }),
                },
                fields: [
                  { type: "string", name: "badge", label: "Štítek kroku" },
                  { type: "string", name: "title", label: "Název kroku" },
                  { type: "string", name: "desc", label: "Popis kroku", ui: { component: "textarea" } },
                ],
              },
              {
                type: "object",
                name: "poster",
                label: "Obrázkový poster s deskovkami",
                fields: [
                  { type: "image", name: "image", label: "Obrázek deskových her / Doučovny" },
                  { type: "string", name: "tag", label: "Štítek (např. Atmosféra naší doučovny)" },
                  { type: "string", name: "title", label: "Nadpis posteru" },
                  { type: "string", name: "desc", label: "Popis posteru", ui: { component: "textarea" } },
                ],
              },
              {
                type: "object",
                name: "bottomCta",
                label: "Spodní výzva / banner lekce",
                fields: [
                  { type: "string", name: "title", label: "Nadpis výzvy" },
                  { type: "string", name: "desc", label: "Popis výzvy" },
                  { type: "string", name: "ctaText", label: "Text tlačítka" },
                  { type: "string", name: "ctaLink", label: "Cíl odkazu" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "timeline",
            label: "Časová osa lekce (60 minut)",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit Časovou osu 60 min lekce na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Hlavní nadpis" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "calloutTitle", label: "Výzva/Garance - nadpis" },
              { type: "string", name: "calloutDesc", label: "Výzva/Garance - popis", ui: { component: "textarea" } },
              { type: "string", name: "calloutCtaText", label: "Výzva/Garance - text tlačítka" },
              { type: "string", name: "calloutCtaLink", label: "Výzva/Garance - odkaz tlačítka" },
              {
                type: "object",
                name: "phases",
                label: "4 Fáze lekce",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: `${item?.time || "Čas"} - ${item?.title || "Fáze"}` }),
                },
                fields: [
                  { type: "string", name: "time", label: "Čas (např. 00–10 min)" },
                  { type: "string", name: "badge", label: "Štítek" },
                  { type: "string", name: "title", label: "Název fáze" },
                  { type: "string", name: "desc", label: "Popis fáze", ui: { component: "textarea" } },
                  { type: "string", name: "highlight", label: "Hlavní přínos" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "location",
            label: "Kde učíme & Doučovna",
            fields: [
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Hlavní nadpis" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "galleryBadge", label: "Fotogalerie - odznáček" },
              { type: "string", name: "galleryTitle", label: "Fotogalerie - nadpis" },
              { type: "string", name: "gallerySubtitle", label: "Fotogalerie - podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "addressTitle", label: "Nadpis adresy" },
              { type: "string", name: "address", label: "Adresa" },
              { type: "string", name: "parkingInfo", label: "Informace o parkování" },
              { type: "string", name: "hoursTitle", label: "Nadpis otevírací doby" },
              { type: "string", name: "hours", label: "Otevírací doba" },
              {
                type: "object",
                name: "perks",
                label: "Výhody lokality",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Výhoda" }),
                },
                fields: [
                  { type: "string", name: "icon", label: "Ikona / Emoji" },
                  { type: "string", name: "title", label: "Název" },
                  { type: "string", name: "desc", label: "Popis", ui: { component: "textarea" } },
                ],
              },
              { type: "string", name: "surroundingTowns", label: "Spádové obce v okolí", ui: { component: "textarea" } },
              {
                type: "object",
                name: "gallery",
                label: "Fotogalerie doučovny",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Fotografie" }),
                },
                fields: [
                  { type: "image", name: "image", label: "Obrázek" },
                  { type: "string", name: "title", label: "Název fotky" },
                  { type: "string", name: "desc", label: "Popisek fotky" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "groupMatcher",
            label: "Rozřazovač do skupinek",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit Rozřazovač do skupinek na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Hlavní nadpis" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "step1Title", label: "Nadpis 1. kroku" },
              { type: "string", name: "step2Title", label: "Nadpis 2. kroku" },
              { type: "string", name: "step3Title", label: "Nadpis 3. kroku" },
              { type: "string", name: "ticketBadge", label: "Zlatá vstupenka - štítek" },
              { type: "string", name: "availabilityBadge", label: "Zlatá vstupenka - dostupnost" },
              { type: "string", name: "gamesLabel", label: "Vybrané hry - nadpis" },
              { type: "string", name: "guaranteeText", label: "Zlatá vstupenka - garance" },
              { type: "string", name: "whatsappText", label: "Text tlačítka WhatsApp" },
              { type: "string", name: "ctaText", label: "Text tlačítka" },
              {
                type: "object",
                name: "grades",
                label: "Krok 1: Volby ročníků",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.title || "Třída" }) },
                fields: [
                  { type: "string", name: "id", label: "ID (1-3, 4-6, 7-9, ss)" },
                  { type: "string", name: "icon", label: "Ikona / Emoji" },
                  { type: "string", name: "title", label: "Název třídy" },
                  { type: "string", name: "age", label: "Věk" },
                  { type: "string", name: "recommendedTitle", label: "Doporučená skupinka - název" },
                  { type: "string", name: "recommendedDesc", label: "Doporučená skupinka - popis", ui: { component: "textarea" } },
                  { type: "string", name: "recommendedGames", label: "Doporučená skupinka - hry", list: true },
                ],
              },
              {
                type: "object",
                name: "interests",
                label: "Krok 2: Volby zájmů",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.title || "Zájem" }) },
                fields: [
                  { type: "string", name: "id", label: "ID (fantasy, words, speed, strategy)" },
                  { type: "string", name: "icon", label: "Ikona / Emoji" },
                  { type: "string", name: "title", label: "Název zájmu" },
                  { type: "string", name: "desc", label: "Příklady her" },
                ],
              },
              {
                type: "object",
                name: "goals",
                label: "Krok 3: Cíle žáka",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.title || "Cíl" }) },
                fields: [
                  { type: "string", name: "id", label: "ID (confidence, grades, fun)" },
                  { type: "string", name: "icon", label: "Ikona / Emoji" },
                  { type: "string", name: "title", label: "Název cíle" },
                  { type: "string", name: "desc", label: "Popis potřeby" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "faq",
            label: "Časté dotazy (FAQ)",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci Časté dotazy (FAQ) na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Nadpis sekce" },
              { type: "string", name: "subtitle", label: "Podnadpis sekce", ui: { component: "textarea" } },
              { type: "string", name: "contactPrompt", label: "Spodní výzva FAQ (otázka)" },
              { type: "string", name: "contactPromptLinkText", label: "Spodní výzva FAQ (text odkazu)" },
              {
                type: "object",
                name: "items",
                label: "Otázky a odpovědi",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.question || "Otázka" }),
                },
                fields: [
                  { type: "string", name: "question", label: "Otázka" },
                  { type: "string", name: "answer", label: "Odpověď", ui: { component: "textarea" } },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "contact",
            label: "Kontaktní informace",
            fields: [
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Nadpis sekce" },
              { type: "string", name: "subtitle", label: "Podnadpis sekce", ui: { component: "textarea" } },
              { type: "image", name: "tutorImage", label: "Fotka lektora u kontaktu" },
              { type: "string", name: "tutorName", label: "Jméno lektora na kartě" },
              { type: "string", name: "tutorCredentials", label: "Titul a zkušenosti" },
              { type: "string", name: "tutorRole", label: "Místo / Doučovna" },
              { type: "string", name: "introText", label: "Úvodní text pod lektorem", ui: { component: "textarea" } },
              { type: "string", name: "email", label: "Kontaktní e-mail" },
              { type: "string", name: "phone", label: "Telefonní číslo" },
              { type: "string", name: "phoneFormatted", label: "Telefon (zobrazený formát)" },
              { type: "string", name: "whatsapp", label: "Odkaz na WhatsApp" },
              { type: "string", name: "whatsappText", label: "Text odkazu na WhatsApp" },
              { type: "string", name: "whatsappMessage", label: "Předvyplněná zpráva pro WhatsApp", ui: { component: "textarea" } },
              { type: "string", name: "location", label: "Místo výuky" },
              { type: "string", name: "hours", label: "Pracovní doba" },
              { type: "string", name: "guaranteeTitle", label: "Karta garance - nadpis" },
              { type: "string", name: "guaranteeDesc", label: "Karta garance - popis", ui: { component: "textarea" } },
              { type: "string", name: "formBadge", label: "Formulář - štítek" },
              { type: "string", name: "formBadgeNote", label: "Formulář - poznámka ke štítku" },
              { type: "string", name: "formTitle", label: "Formulář - nadpis" },
              { type: "string", name: "formSubtitle", label: "Formulář - podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "programLabel", label: "Formulář - popisek výběru programu" },
              { type: "string", name: "formatLabel", label: "Formulář - popisek formy výuky" },
              { type: "string", name: "formatInPersonTitle", label: "Formulář - volba osobně nadpis" },
              { type: "string", name: "formatInPersonNote", label: "Formulář - volba osobně popisek" },
              { type: "string", name: "formatOnlineTitle", label: "Formulář - volba online nadpis" },
              { type: "string", name: "formatOnlineNote", label: "Formulář - volba online popisek" },
              { type: "string", name: "formatUndecidedTitle", label: "Formulář - volba nerozhodnuto nadpis" },
              { type: "string", name: "formatUndecidedNote", label: "Formulář - volba nerozhodnuto popisek" },
              { type: "string", name: "parentNameLabel", label: "Formulář - popisek jméno rodiče" },
              { type: "string", name: "childNameLabel", label: "Formulář - popisek jméno a věk dítěte" },
              { type: "string", name: "phoneLabel", label: "Formulář - popisek telefonní číslo" },
              { type: "string", name: "emailLabel", label: "Formulář - popisek e-mailová adresa" },
              { type: "string", name: "levelLabel", label: "Formulář - popisek třída/úroveň" },
              { type: "string", name: "levelLabelNote", label: "Formulář - poznámka k úrovni" },
              { type: "string", name: "daysLabel", label: "Formulář - popisek dnů" },
              { type: "string", name: "daysNote", label: "Formulář - poznámka ke dnům" },
              { type: "string", name: "daysTimeNote", label: "Formulář - časová poznámka" },
              { type: "string", name: "messageLabel", label: "Formulář - popisek poznámky" },
              { type: "string", name: "stepsTitle", label: "Formulář - nadpis kroků po odeslání" },
              { type: "string", name: "step1Text", label: "Formulář - krok 1 text" },
              { type: "string", name: "step2Text", label: "Formulář - krok 2 text" },
              { type: "string", name: "step3Text", label: "Formulář - krok 3 text" },
              { type: "string", name: "submitButtonText", label: "Formulář - text tlačítka" },
              { type: "string", name: "securityNote", label: "Formulář - bezpečnostní poznámka" },
              { type: "string", name: "web3formsKey", label: "Web3Forms Access Key" },
            ],
          },
          {
            type: "object",
            name: "footer",
            label: "Patička webu",
            fields: [
              { type: "string", name: "brandName", label: "Název akademie" },
              { type: "string", name: "brandTagline", label: "Slogan akademie" },
              { type: "string", name: "description", label: "Popis o akademii", ui: { component: "textarea" } },
              { type: "string", name: "locationNote", label: "Poznámka s adresou" },
              { type: "string", name: "navTitle", label: "Nadpis rychlé navigace" },
              {
                type: "object",
                name: "navLinks",
                label: "Odkazy v rychlé navigaci",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.label || "Odkaz" }) },
                fields: [
                  { type: "string", name: "label", label: "Text odkazu" },
                  { type: "string", name: "href", label: "Cíl odkazu" },
                ],
              },
              { type: "string", name: "contactTitle", label: "Nadpis kontaktu v patičce" },
              { type: "string", name: "icoInfo", label: "IČO informace (v kontaktu)" },
              { type: "string", name: "commuteNote", label: "Poznámka k dostupnosti obcí" },
              { type: "string", name: "bottomCtaText", label: "Spodní odkaz na 1. lekci" },
              { type: "string", name: "adminLinkText", label: "Spodní odkaz na Admin" },
              { type: "string", name: "copyright", label: "Copyright text" },
              { type: "string", name: "legalRegistryInfo", label: "Zápis v rejstříku (spodní řádek)" },
              { type: "string", name: "privacyLinkText", label: "Text odkazu Ochrana údajů" },
              { type: "string", name: "termsLinkText", label: "Text odkazu Obchodní podmínky" },
            ],
          },
          {
            type: "object",
            name: "stickyCta",
            label: "Mobilní plovoucí lišta",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit mobilní plovoucí lištu?" },
              { type: "string", name: "text", label: "Text výzvy" },
              { type: "string", name: "buttonText", label: "Text tlačítka" },
            ],
          },
        ],
      },
      {
        name: "legal",
        label: "Právní dokumenty (GDPR & VOP)",
        path: "content/legal",
        format: "json",
        ui: {
          router: ({ document }) => {
            if (document._sys.filename === "privacy") {
              return "/ochrana-osobnich-udaju";
            }
            if (document._sys.filename === "terms") {
              return "/obchodni-podminky";
            }
            return undefined;
          },
        },
        fields: [
          {
            type: "string",
            name: "backLinkText",
            label: "Text tlačítka zpět na hlavní stránku",
          },
          {
            type: "string",
            name: "title",
            label: "Hlavní nadpis stránky",
            isTitle: true,
            required: true,
          },
          {
            type: "string",
            name: "seoDescription",
            label: "SEO Popis pro vyhledávače",
            ui: { component: "textarea" },
          },
          {
            type: "string",
            name: "badge",
            label: "Horní odznáček / Štítek",
          },
          {
            type: "string",
            name: "subtitle",
            label: "Úvodní popis stránky",
            ui: { component: "textarea" },
          },
          {
            type: "string",
            name: "effectiveDate",
            label: "Datum účinnosti (např. 1. září 2025)",
          },
          {
            type: "string",
            name: "locationNote",
            label: "Poznámka k místu",
          },
          {
            type: "string",
            name: "clientNote",
            label: "Definice klienta (VOP sekce 1)",
            ui: { component: "textarea" },
          },
          {
            type: "string",
            name: "contactBoxTitle",
            label: "Spodní box - nadpis dotazu",
          },
          {
            type: "string",
            name: "contactBoxSubtitle",
            label: "Spodní box - podnadpis dotazu",
            ui: { component: "textarea" },
          },
          {
            type: "object",
            name: "adminInfo",
            label: "Údaje o správci (Zásady ochrany údajů)",
            fields: [
              { type: "string", name: "name", label: "Jméno a příjmení" },
              { type: "string", name: "ico", label: "IČO" },
              { type: "string", name: "address", label: "Sídlo a adresa" },
              { type: "string", name: "registry", label: "Živnostenský zápis" },
              { type: "string", name: "taxStatus", label: "Daňový status (např. Neplátce DPH)" },
              { type: "string", name: "email", label: "Kontaktní e-mail" },
              { type: "string", name: "phone", label: "Kontaktní telefon" },
            ],
          },
          {
            type: "object",
            name: "providerInfo",
            label: "Údaje o poskytovateli (Obchodní podmínky)",
            fields: [
              { type: "string", name: "name", label: "Jméno a příjmení" },
              { type: "string", name: "ico", label: "IČO" },
              { type: "string", name: "address", label: "Sídlo a adresa" },
              { type: "string", name: "registry", label: "Živnostenský zápis" },
              { type: "string", name: "taxStatus", label: "Daňový status" },
              { type: "string", name: "email", label: "Kontaktní e-mail" },
              { type: "string", name: "phone", label: "Kontaktní telefon" },
            ],
          },
          {
            type: "object",
            name: "sections",
            label: "Jednotlivé sekce a odstavce",
            list: true,
            ui: {
              itemProps: (item) => ({
                label: `${item?.number ? item.number + '. ' : ''}${item?.title || 'Sekce'}`,
              }),
            },
            fields: [
              { type: "string", name: "number", label: "Číslo sekce" },
              { type: "string", name: "title", label: "Nadpis sekce", required: true },
              { type: "string", name: "content", label: "Text sekce", ui: { component: "textarea" } },
              {
                type: "object",
                name: "bullets",
                label: "Odrážky / Seznam (volitelné)",
                list: true,
                fields: [
                  { type: "string", name: "label", label: "Tučný název odrážky" },
                  { type: "string", name: "text", label: "Text odrážky", ui: { component: "textarea" } },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
});
