import { defineConfig } from "tinacms";

const branch =
  process.env.GITHUB_BRANCH ||
  process.env.VERCEL_GIT_COMMIT_REF ||
  process.env.HEAD ||
  "main";

export default defineConfig({
  branch,
  clientId: process.env.PUBLIC_TINA_CLIENT_ID || "",
  token: process.env.TINA_TOKEN || "",
  build: {
    outputFolder: "admin",
    publicFolder: "public",
  },
  media: {
    tina: {
      mediaRoot: "uploads",
      publicFolder: "public",
    },
  },
  schema: {
    collections: [
      {
        name: "page",
        label: "Obsah webu",
        path: "content/pages",
        format: "json",
        ui: {
          router: ({ document }) => {
            if (document._sys.filename === "home") {
              return "/";
            }
            return undefined;
          },
        },
        fields: [
          {
            type: "string",
            name: "title",
            label: "Název stránky (SEO Titulek)",
            isTitle: true,
            required: true,
          },
          {
            type: "object",
            name: "navbar",
            label: "Hlavička & Navigace",
            fields: [
              { type: "string", name: "brandName", label: "Název značky" },
              { type: "string", name: "brandTagline", label: "Podtitul značky" },
              { type: "string", name: "ctaText", label: "Text tlačítka v menu" },
              {
                type: "object",
                name: "navLinks",
                label: "Odkazy v horním menu",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.label || "Odkaz" }),
                },
                fields: [
                  { type: "string", name: "label", label: "Text odkazu" },
                  { type: "string", name: "href", label: "Cíl odkazu (#sekce)" },
                  { type: "string", name: "badge", label: "Štítek (např. 1. zdarma)" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "hero",
            label: "Hero sekce",
            fields: [
              { type: "string", name: "badge", label: "Horní odznáček / Tagline" },
              { type: "string", name: "title", label: "Hlavní nadpis" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "ctaPrimaryText", label: "Text primárního tlačítka" },
              { type: "string", name: "ctaPrimaryLink", label: "Odkaz primárního tlačítka" },
              { type: "string", name: "ctaSecondaryText", label: "Text sekundárního tlačítka" },
              { type: "string", name: "ctaSecondaryLink", label: "Odkaz sekundárního tlačítka" },
              {
                type: "object",
                name: "card",
                label: "Karta Josefa & Hlasová ukázka (vpravo)",
                fields: [
                  { type: "string", name: "teacherName", label: "Jméno lektora" },
                  { type: "string", name: "teacherRole", label: "Podtitul / Vzdělání (např. BBA Melbourne • 25+ let v ČR)" },
                  { type: "string", name: "teacherTag", label: "Specializace (např. Australský přízvuk & výuka hrou)" },
                  { type: "string", name: "badgeText", label: "Odznáček na kartě (např. 1. lekce ZDARMA)" },
                  {
                    type: "object",
                    name: "audio",
                    label: "Hlasový přehrávač Josefa",
                    fields: [
                      { type: "string", name: "title", label: "Nadpis přehrávače zvuku" },
                      { type: "string", name: "subtitlePrompt", label: "Výzva k přehrání (např. Klikněte pro přehrání)" },
                      {
                        type: "object",
                        name: "phrases",
                        label: "Zvukové fráze",
                        list: true,
                        ui: {
                          itemProps: (item) => ({ label: `${item?.buttonLabel || item?.id || "Fráze"}` }),
                        },
                        fields: [
                          { type: "string", name: "id", label: "Klíč zvuku (gday, dice, noworries)" },
                          { type: "string", name: "buttonLabel", label: "Text na tlačítku" },
                          { type: "string", name: "short", label: "Zkrácený text u vln" },
                          { type: "string", name: "en", label: "Anglická věta", ui: { component: "textarea" } },
                          { type: "string", name: "cz", label: "Český překlad věty", ui: { component: "textarea" } },
                        ],
                      },
                    ],
                  },
                  { type: "string", name: "benefit1Title", label: "Výhoda 1 - Nadpis" },
                  { type: "string", name: "benefit1Desc", label: "Výhoda 1 - Podtitul" },
                  { type: "string", name: "benefit2Title", label: "Výhoda 2 - Nadpis" },
                  { type: "string", name: "benefit2Desc", label: "Výhoda 2 - Podtitul" },
                  { type: "string", name: "locationNote", label: "Adresa v kartě" },
                  { type: "string", name: "onlineNote", label: "Online text v kartě" },
                  { type: "string", name: "ctaText", label: "Text odkazu (např. Rezervovat →)" },
                  { type: "string", name: "ctaLink", label: "Cíl odkazu" },
                ],
              },
              {
                type: "object",
                name: "stats",
                label: "Statistiky & Důvěryhodnost",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: `${item?.number || "Statistika"} - ${item?.label || ""}` }),
                },
                fields: [
                  { type: "string", name: "number", label: "Číslo (např. 10+ let)" },
                  { type: "string", name: "label", label: "Popis (např. praxe v ČR)" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "audience",
            label: "3 Cílové skupiny (ZŠ, SŠ, Dospělí)",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci Programy & Hry na webu?" },
              { type: "string", name: "badge", label: "Odznáček sekce" },
              { type: "string", name: "title", label: "Nadpis sekce" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              {
                type: "object",
                name: "segments",
                label: "Karty cílových skupin",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: `${item?.title || "Skupina"} (${item?.age || ""})` }),
                },
                fields: [
                  { type: "string", name: "id", label: "Identifikátor (zs, ss, dospeli)" },
                  { type: "string", name: "icon", label: "Ikona (emoji např. 🎒, 🎓, 💼)" },
                  { type: "string", name: "title", label: "Název skupiny" },
                  { type: "string", name: "age", label: "Věková kategorie (např. 6–15 let)" },
                  { type: "string", name: "badge", label: "Štítek" },
                  { type: "string", name: "highlight", label: "Hlavní tahák / přínos" },
                  { type: "string", name: "description", label: "Podrobný popis", ui: { component: "textarea" } },
                  { type: "string", name: "points", label: "Výhody a body", list: true },
                  { type: "string", name: "ctaText", label: "Text tlačítka" },
                  { type: "string", name: "ctaLink", label: "Odkaz tlačítka" },
                ],
              },
              {
                type: "object",
                name: "kidsPrograms",
                label: "Programy pro žáky ZŠ",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: `${item?.title || "Program"} (${item?.age || ""})` }),
                },
                fields: [
                  { type: "string", name: "id", label: "Identifikátor" },
                  { type: "string", name: "icon", label: "Ikona / Emoji" },
                  { type: "string", name: "title", label: "Název programu" },
                  { type: "string", name: "age", label: "Věk a velikost skupinky" },
                  { type: "string", name: "badge", label: "Štítek" },
                  { type: "string", name: "highlight", label: "Hlavní tahák / přínos" },
                  { type: "string", name: "description", label: "Popis programu", ui: { component: "textarea" } },
                  { type: "string", name: "games", label: "Představené hry", list: true },
                  { type: "string", name: "points", label: "Body výhod", list: true },
                  { type: "string", name: "capacityNote", label: "Stav volných míst (např. 🟢 Volná 3 místa)" },
                  { type: "string", name: "ctaText", label: "Text tlačítka" },
                  { type: "string", name: "ctaLink", label: "Odkaz tlačítka" },
                ],
              },
              {
                type: "object",
                name: "waitingList",
                label: "Čekací listina pro SŠ a dospělé",
                fields: [
                  { type: "string", name: "badge", label: "Štítek" },
                  { type: "string", name: "title", label: "Nadpis" },
                  { type: "string", name: "description", label: "Popis", ui: { component: "textarea" } },
                  { type: "string", name: "ctaText", label: "Text tlačítka" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "scio",
            label: "Sekce SCIO & Přijímačky na SŠ",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci SCIO na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Hlavní nadpis" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "tagline", label: "Slogan" },
              { type: "string", name: "features", label: "Body a výhody přípravy", list: true },
              { type: "string", name: "ctaText", label: "Text tlačítka" },
              { type: "string", name: "ctaLink", label: "Odkaz tlačítka" },
            ],
          },
          {
            type: "object",
            name: "about",
            label: "Sekce O lektorovi & Metodika",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci O lektorovi na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Nadpis sekce" },
              { type: "string", name: "teacherName", label: "Jméno lektora" },
              { type: "string", name: "role", label: "Titul / Pozice" },
              { type: "string", name: "bio", label: "Životopis a přístup", ui: { component: "textarea" } },
              { type: "string", name: "quote", label: "Citát / Motto", ui: { component: "textarea" } },
              {
                type: "object",
                name: "pillars",
                label: "4 Pilíře výuky",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Pilíř" }),
                },
                fields: [
                  { type: "string", name: "icon", label: "Ikona / Emoji" },
                  { type: "string", name: "title", label: "Název pilíře" },
                  { type: "string", name: "description", label: "Popis pilíře", ui: { component: "textarea" } },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "pricing",
            label: "Ceník a balíčky",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci Ceník na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Nadpis sekce" },
              { type: "string", name: "subtitle", label: "Podnadpis sekce", ui: { component: "textarea" } },
              { type: "string", name: "guarantee", label: "Garance spokojenosti", ui: { component: "textarea" } },
              {
                type: "object",
                name: "tiers",
                label: "Cenové balíčky",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: `${item?.name || "Balíček"} - ${item?.price || ""}` }),
                },
                fields: [
                  { type: "string", name: "name", label: "Název balíčku" },
                  { type: "string", name: "price", label: "Cena" },
                  { type: "string", name: "period", label: "Čas / Počet lekcí" },
                  { type: "string", name: "description", label: "Popis balíčku", ui: { component: "textarea" } },
                  { type: "boolean", name: "isPopular", label: "Zvýraznit jako nejpopulárnější?" },
                  { type: "string", name: "badge", label: "Štítek" },
                  { type: "string", name: "features", label: "Položky v ceně", list: true },
                  { type: "string", name: "ctaText", label: "Text tlačítka" },
                  { type: "string", name: "ctaLink", label: "Odkaz tlačítka" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "comparison",
            label: "Srovnávací tabulka (Škola vs Doučování vs Valek)",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit Srovnávací tabulku na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Nadpis srovnání" },
              { type: "string", name: "subtitle", label: "Podnadpis srovnání", ui: { component: "textarea" } },
              {
                type: "object",
                name: "columns",
                label: "Srovnávací sloupce",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Sloupec" }),
                },
                fields: [
                  { type: "string", name: "type", label: "Typ (school, private, valek)" },
                  { type: "string", name: "title", label: "Název" },
                  { type: "string", name: "subtitle", label: "Podtitul (počet dětí)" },
                  { type: "string", name: "badge", label: "Štítek" },
                  { type: "string", name: "price", label: "Cena" },
                  { type: "string", name: "priceNote", label: "Poznámka k ceně" },
                  { type: "string", name: "speakingTime", label: "Prostor pro mluvení" },
                  { type: "string", name: "atmosphere", label: "Atmosféra & stres" },
                  { type: "string", name: "method", label: "Metodika & hry" },
                  { type: "string", name: "accent", label: "Přízvuk lektora" },
                  { type: "string", name: "motivation", label: "Motivace & výsledky" },
                  { type: "boolean", name: "isWinner", label: "Je vítěz srovnání? (Zlaté zvýraznění)" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "testimonials",
            label: "Reference a recenze",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci Reference na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Nadpis sekce" },
              { type: "string", name: "subtitle", label: "Podnadpis sekce", ui: { component: "textarea" } },
              { type: "string", name: "ratingScore", label: "Skóre hodnocení" },
              { type: "string", name: "ratingNote", label: "Poznámka k hodnocení" },
              {
                type: "object",
                name: "reviews",
                label: "Recenze studentů a rodičů",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: `${item?.name || "Student"} (${item?.role || ""})` }),
                },
                fields: [
                  { type: "string", name: "name", label: "Jméno studenta / rodiče" },
                  { type: "string", name: "role", label: "Pozice / Role a město" },
                  { type: "string", name: "location", label: "Město" },
                  { type: "number", name: "rating", label: "Počet hvězdiček (1-5)" },
                  { type: "string", name: "highlight", label: "Hlavní přínos / Zvýraznění" },
                  { type: "string", name: "quote", label: "Citace / Zkušenost", ui: { component: "textarea" } },
                  { type: "string", name: "avatarText", label: "Iniciály" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "howItWorks",
            label: "Metodika & Hry",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci Jak výuka hrou funguje na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Hlavní nadpis" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "quote", label: "Citát / Zvýrazněná věta" },
              {
                type: "object",
                name: "gameSpotlights",
                label: "Představené deskovky",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Deskovka" }),
                },
                fields: [
                  { type: "string", name: "icon", label: "Ikona / Emoji" },
                  { type: "string", name: "title", label: "Název hry" },
                  { type: "string", name: "tag", label: "Zaměření" },
                  { type: "string", name: "badge", label: "Štítek / Věk" },
                  { type: "string", name: "accent", label: "Barevný akcent (CSS třída)" },
                  { type: "string", name: "desc", label: "Popis přínosu", ui: { component: "textarea" } },
                  { type: "string", name: "phrases", label: "Ukázky vět ze hry", list: true },
                ],
              },
              {
                type: "object",
                name: "steps",
                label: "3 Kroky lekce",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Krok" }),
                },
                fields: [
                  { type: "string", name: "badge", label: "Štítek kroku" },
                  { type: "string", name: "title", label: "Název kroku" },
                  { type: "string", name: "desc", label: "Popis kroku", ui: { component: "textarea" } },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "timeline",
            label: "Časová osa lekce (60 minut)",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit Časovou osu 60 min lekce na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Hlavní nadpis" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              {
                type: "object",
                name: "phases",
                label: "4 Fáze lekce",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: `${item?.time || "Čas"} - ${item?.title || "Fáze"}` }),
                },
                fields: [
                  { type: "string", name: "time", label: "Čas (např. 00–10 min)" },
                  { type: "string", name: "badge", label: "Štítek" },
                  { type: "string", name: "title", label: "Název fáze" },
                  { type: "string", name: "desc", label: "Popis fáze", ui: { component: "textarea" } },
                  { type: "string", name: "highlight", label: "Hlavní přínos" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "location",
            label: "Kde učíme & Doučovna",
            fields: [
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Hlavní nadpis" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "addressTitle", label: "Nadpis adresy" },
              { type: "string", name: "address", label: "Adresa" },
              { type: "string", name: "parkingInfo", label: "Informace o parkování" },
              { type: "string", name: "hoursTitle", label: "Nadpis otevírací doby" },
              { type: "string", name: "hours", label: "Otevírací doba" },
              {
                type: "object",
                name: "perks",
                label: "Výhody lokality",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Výhoda" }),
                },
                fields: [
                  { type: "string", name: "icon", label: "Ikona / Emoji" },
                  { type: "string", name: "title", label: "Název" },
                  { type: "string", name: "desc", label: "Popis", ui: { component: "textarea" } },
                ],
              },
              { type: "string", name: "surroundingTowns", label: "Spádové obce v okolí", ui: { component: "textarea" } },
              {
                type: "object",
                name: "gallery",
                label: "Fotogalerie doučovny",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.title || "Fotografie" }),
                },
                fields: [
                  { type: "image", name: "image", label: "Obrázek" },
                  { type: "string", name: "title", label: "Název fotky" },
                  { type: "string", name: "desc", label: "Popisek fotky" },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "groupMatcher",
            label: "Rozřazovač do skupinek",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit Rozřazovač do skupinek na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Hlavní nadpis" },
              { type: "string", name: "subtitle", label: "Podnadpis", ui: { component: "textarea" } },
              { type: "string", name: "step1Title", label: "Nadpis 1. kroku" },
              { type: "string", name: "step2Title", label: "Nadpis 2. kroku" },
              { type: "string", name: "step3Title", label: "Nadpis 3. kroku" },
              { type: "string", name: "ctaText", label: "Text tlačítka" },
            ],
          },
          {
            type: "object",
            name: "faq",
            label: "Časté dotazy (FAQ)",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit sekci Časté dotazy (FAQ) na webu?" },
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Nadpis sekce" },
              { type: "string", name: "subtitle", label: "Podnadpis sekce", ui: { component: "textarea" } },
              {
                type: "object",
                name: "items",
                label: "Otázky a odpovědi",
                list: true,
                ui: {
                  itemProps: (item) => ({ label: item?.question || "Otázka" }),
                },
                fields: [
                  { type: "string", name: "question", label: "Otázka" },
                  { type: "string", name: "answer", label: "Odpověď", ui: { component: "textarea" } },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "contact",
            label: "Kontaktní informace",
            fields: [
              { type: "string", name: "badge", label: "Odznáček" },
              { type: "string", name: "title", label: "Nadpis sekce" },
              { type: "string", name: "subtitle", label: "Podnadpis sekce", ui: { component: "textarea" } },
              { type: "string", name: "email", label: "Kontaktní e-mail" },
              { type: "string", name: "phone", label: "Telefonní číslo" },
              { type: "string", name: "phoneFormatted", label: "Telefon (zobrazený formát)" },
              { type: "string", name: "whatsapp", label: "Odkaz na WhatsApp" },
              { type: "string", name: "location", label: "Místo výuky" },
              { type: "string", name: "hours", label: "Pracovní doba" },
              { type: "string", name: "web3formsKey", label: "Web3Forms Access Key" },
            ],
          },
          {
            type: "object",
            name: "footer",
            label: "Patička webu",
            fields: [
              { type: "string", name: "description", label: "Popis o akademii", ui: { component: "textarea" } },
              { type: "string", name: "locationNote", label: "Poznámka s adresou" },
              { type: "string", name: "copyright", label: "Copyright text" },
            ],
          },
          {
            type: "object",
            name: "stickyCta",
            label: "Mobilní plovoucí lišta",
            fields: [
              { type: "boolean", name: "enabled", label: "Zobrazit mobilní plovoucí lištu?" },
              { type: "string", name: "text", label: "Text výzvy" },
              { type: "string", name: "buttonText", label: "Text tlačítka" },
            ],
          },
        ],
      },
    ],
  },
});
